simulation :
    quantiles: [50,]
    prediction:
        model: 'simple_prediction'
        window: 0
    startdate: '2014-01-02'
    enddate: '2015-01-01'
    replenishment:
        model: 'order_ten_replenishment'
    input_file: 'temp.csv'
