simulation :
    quantiles: [10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 98, 99]
    prediction:
        model: 'ewma_prediction'
    startdate: '2014-01-02'
    enddate: '2015-01-01'
    replenishment:
        model: 'replenishment'
    input_file: 'temp.csv'
